// Crawls the food composition data that powers viendinhduong.vn's food lookup
// page (https://viendinhduong.vn/vi/cong-cu-va-tien-ich/gia-tri-dinh-duong-thuc-pham)
// and emits an idempotent SQL seed file matching the NutriCare schema
// (nutrient, food_item, food_item_tag, food_item_nutrient).
//
// There is no published/stable API for this data. The site itself calls this
// endpoint from the browser to render the search page, so it is the same data
// a normal user would see - this script just automates paging through it.
//
// Usage: node crawl.mjs [--out ../../src/main/resources/seed/food_nutrient_data.sql]

import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const API_BASE = "https://viendinhduong.vn/api/fe/foodNatunal/getPageFoodData";
const PAGE_SIZE = 200;
const SOURCE_PREFIX = "vdd"; // tag namespace: vdd:<food code>
const ENERGY_NUTRIENT = { code: "energy", name: "Năng lượng", name_en: "Energy", unit: "kcal" };

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outArg = process.argv.indexOf("--out");
const outPath = outArg !== -1
    ? path.resolve(process.cwd(), process.argv[outArg + 1])
    : path.resolve(__dirname, "output", "seed_food_nutrient_data.sql");

function sqlString(value) {
    return `'${String(value).replace(/'/g, "''")}'`;
}

function sqlNumber(value) {
    if (typeof value !== "number" || Number.isNaN(value)) {
        throw new Error(`Expected a finite number, got ${value}`);
    }
    return value.toString();
}

async function fetchAllFoods() {
    const foods = [];
    let page = 1;
    let total = Infinity;

    while (foods.length < total) {
        const url = `${API_BASE}?page=${page}&pageSize=${PAGE_SIZE}`;
        const res = await fetch(url, { headers: { Accept: "application/json" } });
        if (!res.ok) {
            throw new Error(`Request failed (${res.status}) for ${url}`);
        }
        const body = await res.json();
        total = body.total;
        foods.push(...body.data);
        console.log(`Fetched page ${page}: ${body.data.length} foods (${foods.length}/${total})`);
        if (body.data.length === 0) break;
        page += 1;
    }

    return foods;
}

function collectNutrientDictionary(foods) {
    const dict = new Map();
    dict.set(ENERGY_NUTRIENT.code, ENERGY_NUTRIENT);

    for (const food of foods) {
        for (const n of food.nutrition) {
            const existing = dict.get(n.key);
            if (existing && (existing.unit !== n.unit || existing.name !== n.name)) {
                console.warn(
                    `Nutrient "${n.key}" has conflicting definitions: ` +
                    `${JSON.stringify(existing)} vs ${JSON.stringify({ name: n.name, name_en: n.name_en, unit: n.unit })}. Keeping the first one seen.`
                );
                continue;
            }
            dict.set(n.key, { code: n.key, name: n.name, name_en: n.name_en, unit: n.unit });
        }
    }

    return dict;
}

function buildSql(foods, nutrientDict) {
    const lines = [];
    lines.push("-- Auto-generated by tools/food-crawler/crawl.mjs");
    lines.push(`-- Source: viendinhduong.vn food composition lookup, crawled ${new Date().toISOString()}`);
    lines.push("-- Safe to re-run: nutrients upsert by code, foods are matched/skipped via a");
    lines.push(`-- 'source:${SOURCE_PREFIX}:<code>'-style tag, and nutrient amounts upsert by (food_item_id, nutrient_id).`);
    lines.push("");

    lines.push("-- Nutrients");
    for (const n of [...nutrientDict.values()].sort((a, b) => a.code.localeCompare(b.code))) {
        const name = n.name || n.name_en || n.code;
        lines.push(
            `INSERT INTO nutrient (code, name, unit) VALUES (${sqlString(n.code)}, ${sqlString(name)}, ${sqlString(n.unit)}) ` +
            `ON CONFLICT (code) DO NOTHING;`
        );
    }
    lines.push("");

    lines.push("-- Food items and their nutrient amounts (per 100g)");
    let skippedNoName = 0;
    for (const food of foods) {
        if (!food.name_vi) {
            skippedNoName += 1;
            continue;
        }
        const tag = `source:${SOURCE_PREFIX}:${food.code}`;
        const name = food.name_vi;
        const category = food.category || null;

        lines.push(
            `WITH ins AS (\n` +
            `    INSERT INTO food_item (name, category, serving_size_g)\n` +
            `    SELECT ${sqlString(name)}, ${category ? sqlString(category) : "NULL"}, 100\n` +
            `    WHERE NOT EXISTS (SELECT 1 FROM food_item_tag WHERE tag = ${sqlString(tag)})\n` +
            `    RETURNING id\n` +
            `)\n` +
            `INSERT INTO food_item_tag (food_item_id, tag)\n` +
            `SELECT id, ${sqlString(tag)} FROM ins;`
        );

        const entries = food.nutrition.filter((e) => typeof e.value === "number" && !Number.isNaN(e.value));
        if (typeof food.energy === "number") {
            entries.push({ key: ENERGY_NUTRIENT.code, value: food.energy });
        }
        if (entries.length > 0) {
            const codes = entries.map((e) => sqlString(e.key)).join(", ");
            const amounts = entries.map((e) => sqlNumber(e.value)).join(", ");
            lines.push(
                `INSERT INTO food_item_nutrient (food_item_id, nutrient_id, amount_per_100g)\n` +
                `SELECT t.food_item_id, n.id, v.amount\n` +
                `FROM food_item_tag t\n` +
                `JOIN LATERAL unnest(ARRAY[${codes}]::varchar[], ARRAY[${amounts}]::double precision[]) AS v(code, amount) ON true\n` +
                `JOIN nutrient n ON n.code = v.code\n` +
                `WHERE t.tag = ${sqlString(tag)}\n` +
                `ON CONFLICT (food_item_id, nutrient_id) DO UPDATE SET amount_per_100g = EXCLUDED.amount_per_100g;`
            );
        }
        lines.push("");
    }

    if (skippedNoName > 0) {
        console.warn(`Skipped ${skippedNoName} foods with no name_vi.`);
    }

    return lines.join("\n");
}

async function main() {
    console.log("Fetching food composition data from viendinhduong.vn ...");
    const foods = await fetchAllFoods();
    console.log(`Fetched ${foods.length} foods total.`);

    const nutrientDict = collectNutrientDictionary(foods);
    console.log(`Collected ${nutrientDict.size} distinct nutrients.`);

    const sql = buildSql(foods, nutrientDict);
    await writeFile(outPath, sql, "utf-8");
    console.log(`Wrote ${outPath}`);
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
