-- Catalog / reference tables (no dependencies)

CREATE TABLE nutrient (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    unit VARCHAR(255) NOT NULL
);

CREATE TABLE nutrition_standard (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(255) NOT NULL UNIQUE,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(1000)
);

-- Profile aggregate

CREATE TABLE profile (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        INTEGER NOT NULL,
    name           VARCHAR(255) NOT NULL,
    group_type     VARCHAR(30) NOT NULL,
    sex_type       VARCHAR(30) NOT NULL,
    birth_date     DATE NOT NULL,
    weight_kg      DOUBLE PRECISION NOT NULL,
    height_cm      DOUBLE PRECISION NOT NULL,
    activity_level VARCHAR(30) NOT NULL,
    trimester      INTEGER,
    created_at     TIMESTAMP NOT NULL,
    updated_at     TIMESTAMP NOT NULL
);

CREATE TABLE profile_condition (
    profile_id INTEGER NOT NULL REFERENCES profile (id) ON DELETE CASCADE,
    condition  VARCHAR(255) NOT NULL,
    PRIMARY KEY (profile_id, condition)
);

-- FoodItem aggregate

CREATE TABLE food_item (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255) NOT NULL,
    category          VARCHAR(255),
    serving_size_g    DOUBLE PRECISION NOT NULL,
    owner_profile_id  INTEGER REFERENCES profile (id) ON DELETE RESTRICT
);

CREATE TABLE food_item_tag (
    food_item_id INTEGER NOT NULL REFERENCES food_item (id) ON DELETE CASCADE,
    tag          VARCHAR(255) NOT NULL,
    PRIMARY KEY (food_item_id, tag)
);

CREATE TABLE food_item_nutrient (
    food_item_id    INTEGER NOT NULL REFERENCES food_item (id) ON DELETE CASCADE,
    nutrient_id     INTEGER NOT NULL REFERENCES nutrient (id) ON DELETE RESTRICT,
    amount_per_100g DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (food_item_id, nutrient_id)
);

-- IntakeLog aggregate

CREATE TABLE intake_log (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id INTEGER NOT NULL REFERENCES profile (id) ON DELETE RESTRICT,
    log_date   DATE NOT NULL
);

CREATE TABLE intake_entry (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intake_log_id INTEGER NOT NULL REFERENCES intake_log (id) ON DELETE CASCADE,
    food_item_id  INTEGER NOT NULL REFERENCES food_item (id) ON DELETE RESTRICT,
    quantity_g    DOUBLE PRECISION NOT NULL,
    meal_slot     VARCHAR(30) NOT NULL
);

-- Menu aggregate

CREATE TABLE menu (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id  INTEGER NOT NULL REFERENCES profile (id) ON DELETE RESTRICT,
    menu_date   DATE NOT NULL,
    label       VARCHAR(255),
    menu_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT'
);

CREATE TABLE menu_item (
    menu_id      INTEGER NOT NULL REFERENCES menu (id) ON DELETE CASCADE,
    food_item_id INTEGER NOT NULL REFERENCES food_item (id) ON DELETE RESTRICT,
    meal_slot    VARCHAR(30) NOT NULL,
    quantity_g   DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (menu_id, food_item_id, meal_slot)
);

-- Calculation reference tables (depend on nutrition_standard / nutrient)

CREATE TABLE nutrient_requirement (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    standard_id     INTEGER NOT NULL REFERENCES nutrition_standard (id) ON DELETE RESTRICT,
    group_type      VARCHAR(30) NOT NULL,
    nutrient_id     INTEGER NOT NULL REFERENCES nutrient (id) ON DELETE RESTRICT,
    age_months_min  INTEGER NOT NULL,
    age_months_max  INTEGER NOT NULL,
    trimester       INTEGER,
    recommended_val DOUBLE PRECISION NOT NULL,
    max_val         DOUBLE PRECISION
);

CREATE TABLE energy_coefficient (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    standard_id        INTEGER NOT NULL REFERENCES nutrition_standard (id) ON DELETE RESTRICT,
    group_type         VARCHAR(30) NOT NULL,
    sex_type           VARCHAR(30) NOT NULL,
    age_months_min     INTEGER NOT NULL,
    age_months_max     INTEGER NOT NULL,
    trimester          INTEGER,
    weight_coefficient DOUBLE PRECISION NOT NULL,
    height_coefficient DOUBLE PRECISION NOT NULL,
    intercept          DOUBLE PRECISION NOT NULL
);

-- CalculationResult aggregate

CREATE TABLE calculation_result (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id     INTEGER NOT NULL REFERENCES profile (id) ON DELETE RESTRICT,
    standard_id    INTEGER NOT NULL REFERENCES nutrition_standard (id) ON DELETE RESTRICT,
    calculated_at  TIMESTAMP NOT NULL,
    calorie_target DOUBLE PRECISION NOT NULL
);

CREATE TABLE calculation_result_nutrient_target (
    calculation_result_id INTEGER NOT NULL REFERENCES calculation_result (id) ON DELETE CASCADE,
    nutrient_id           INTEGER NOT NULL REFERENCES nutrient (id) ON DELETE RESTRICT,
    target_amount_g       DOUBLE PRECISION NOT NULL,
    max_amount_g          DOUBLE PRECISION,
    PRIMARY KEY (calculation_result_id, nutrient_id)
);

CREATE TABLE calculation_result_unresolved_nutrient (
    calculation_result_id INTEGER NOT NULL REFERENCES calculation_result (id) ON DELETE CASCADE,
    nutrient_id           INTEGER NOT NULL REFERENCES nutrient (id) ON DELETE RESTRICT,
    PRIMARY KEY (calculation_result_id, nutrient_id)
);
