CREATE TABLE users (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(30) NOT NULL,
    created_at    TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP NOT NULL
);

ALTER TABLE profile
    ADD CONSTRAINT fk_profile_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT;
